version: '3.3'
services:
  swagger-ui:
    image: sheypoor/openapi-ui:latest
    container_name: swagger-ui
    volumes: 
      - './urls.yaml:/app/config/urls.yaml:ro'
    environment: 
      APP_PORT: 8000
      CONFIG_MODE: production  # defined in the config file (test/production/...)
    ports:
      - "8000:8000"
    
